### ISSUE TITLE
[Urgent] Do the number of drivers specified in DRIVER_HOSTS have effect when running manually?

### ISSUE THREAD

**Issue by haytham-salhi** [gridgain/yardstick#12]
Hi, 

When running using **manual scripts**, does the number of drivers specified in DRIVER_HOSTS run clients accordingly? In other words, when I specify DRIVER_HOSTS=localhost, it should run one driver. When I specify DRIVER_HOSTS=localhost,localhost, it should run two drivers, and so on. Is that right? I feel it always runs 1 driver regardless how many values you specify!!, **again when using the manual scripts**.

Also, when changing any of values in benchmark.properties file, it is supposed that I don't need to re-build again? That's right? Just wanted to make sure.

Thank you in advance!

**Comment by yzhdanov** [comment]
This will start 2 drivers on localhost. Can you please look at "top" command output?

> Also, when changing any of values in benchmark.properties file, it is supposed that I don't need to re-build again? That's right? Just wanted to make sure.

Yes, you are right.

Thanks!
