### ISSUE TITLE
How to configure third type of entiry (say Locator) in addition to Server and Driver

### ISSUE THREAD

**Issue by rdiyewar** [gridgain/yardstick#2]
I want to benchmark our product using yardstick. 
Our product have following entities:
   1) Locator - for clustor management and discovery, very few in number
   2) Server - stores data, scalable
   3) Client - performs user operation, Driver in case of yardstick

We can configure Server and Client, please let me know how to configure Locator member?

**Comment by niktikhonov** [comment]
Hi,
You can run your `Locator` together with `Servers` and use the same configuration object. You can add additional parameter like ordinal number of `Server` and run `locator` only for with even ordinal numbers. Please see https://github.com/yardstick-benchmarks/yardstick-ignite/blob/master/src/main/java/org/apache/ignite/yardstick/IgniteBenchmarkArguments.java parameter "--nodeNumber".
If your project is open source and you can share, I'll give more ideas.
Thank you for your interest!

**Comment by rdiyewar** [comment]
Thanks for the response. 

My Locator and Servers are separate entities and should run in separate jvm. I can provide sufficient server hosts in SERVER_HOSTS config (say SERVER_HOSTS=host1,hostb,hostc), start locator on one of the host and servers on remaining hosts. Is it possible, if yes, then how do i distiguish between these hosts inside the code. 

The "--nodeNumber" in ignite benchmark is used to count total members in the system i.e. servers + drivers.  The cfg.nodes() returns what it was configured. 

Also, how can i provide per server specific cofiguration. For example i want to start two server so configured it as "SERVER_HOSTS=host1,hostb", now i wan to set different server name to each server in BenchmarkServer.start() method, how this can be acheived.

Thanks,
Rahul Diyewar

**Comment by niktikhonov** [comment]
> My Locator and Servers are separate entities and should run in separate jvm. I can provide sufficient server hosts in SERVER_HOSTS config (say SERVER_HOSTS=host1,hostb,hostc), start locator on one of the host and servers on remaining hosts. Is it possible, if yes, then how do i distiguish between these hosts inside the code.

You need to write additional logic in your `BenchmarkServer.start(BenchmarkConfiguration cfg)`. You can add a server configuration parameter `--locatorHost=host1,hostb` or benchmark property  `LOCATOR_HOST=host1,hostb` and handle it inside `start` method.

``` java
if (locatorHosts.contains(getLocalHost()) {
    // Start locator
}
else {
    // Start server
}
```

> Also, how can i provide per server specific cofiguration. For example i want to start two server so configured it as "SERVER_HOSTS=host1,hostb", now i wan to set different server name to each server in BenchmarkServer.start() method, how this can be acheived.

Yardstick starts servers with the same configuration. You can use just environment properties as hostname, ip and etc.

**Comment by rdiyewar** [comment]
Hun! defining locator hosts at two places is confusing. Isn't ```if ( locatorHosts.contains(getLocalHost()))``` will always return true.

**Comment by rdiyewar** [comment]
Thanks. Is `getLocalHost()` function already availabe or do i need to implement it by my own. 

Do we have some global data structure shared across all servers and drivers?

-rahul

**Comment by niktikhonov** [comment]
> Thanks. Is getLocalHost() function already availabe or do i need to implement it by my own.

No, you need to implement the function. See how to get all hostname and ip. [link](http://atagunov.blogspot.ru/2012/10/get-all-hostnames-and-ip-addresses-from.html)

> Do we have some global data structure shared across all servers and drivers?

Yardstick doesn't have distributed data. I can recommend to use [Apache Ignite](http://apacheignite.readme.io/v1.0/docs/getting-started) for share data. Ignite has simple API and allow create caches on the fly. You can start driver, server and locator with ignite node and simplify share your data.

**Comment by rdiyewar** [comment]
Thanks for the responses. I feel that we should able to distinguish between server (or drivers) which helps us to provide special handeling to specific server instance if required.

Thus, i implemented MemberId support in Yardstick, refer pull request https://github.com/gridgain/yardstick/pull/3 .
