### ISSUE TITLE
It is impossible to use Lambda expressions inside of benchmarks

### ISSUE THREAD

**Issue by glinkaf** [gridgain/yardstick#24]
Hi,

I had a strange problem which took me quite some time to figure out: one of my custom benchmarks was not picked up by Yardstick's BenchmarkLoader - without reporting any error.

Digging into it revealed that the org.reflections dependency used inside of Yardstick is not able to handle Java 8 classes with Lambda expressions. Please update this dependency! I've updated/added the following dependencies and it worked out:
```
<dependency>
    <groupId>org.reflections</groupId>
    <artifactId>reflections</artifactId>
    <version>0.9.11</version>
</dependency>

<!-- Now required for javax.annotation.Nullable availablility. -->
<dependency> 
    <groupId>com.google.code.findbugs</groupId>
    <artifactId>jsr305</artifactId>
    <version>3.0.2</version>
</dependency>
```

See also: [https://github.com/gmuecke/reflections/issues/184](url)

This should be a pretty easy fix, improving the Java 8 compatibility significantly.

_FYI: Adding the above `org.reflections` dependency to your benchmark project's pom will replace the outdated reflections library during the `mvn install` (which worked for me as a workaround)._

**Comment by ntikhonov** [comment]
Hi @glinkaf,
Yes, it's known limitation. Could you open a pull request with this changes? I would glad to merge it.

**Comment by ntikhonov** [comment]
I've pushed the changes to master. https://github.com/gridgain/yardstick/commit/15e1c58f2dff898571e6434f1a147f97c63a4be7
