### ISSUE TITLE
Warmup time should be separate than test time

### ISSUE THREAD

**Issue by rdiyewar** [gridgain/yardstick#8]
It seems that the warm-up time (-w) is part of the test duration (-d), which is confusing. Ideally, warm-up is initial time where system does lots of one time lazy initialization stuff. For bench marking we focus on core operation and thus ignores initial stuff done in warm-up time. 

Test duration is time of interest for which benchmark reports are generated, which should be separate than the warm-up time.

**Comment by yzhdanov** [comment]
Hi! 

Total benchmark run-time is sum of warmup and duration. Probes get reset when warmup finishes. You can check code here - https://github.com/gridgain/yardstick/blob/master/src/main/java/org/yardstickframework/impl/BenchmarkRunner.java
